// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => web;

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Mf4iipzFMcctXnX7Oj_heo9bmjGAvjc',
    appId: '1:1069645309680:web:2dd1d153f052dfe42a0435',
    messagingSenderId: '1069645309680',
    projectId: 'application-servicebo',
    authDomain: 'application-servicebo.firebaseapp.com',
    databaseURL:
        'https://application-servicebo-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'application-servicebo.firebasestorage.app',
    measurementId: 'G-LJYS1VL9HR',
  );
}
